config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations',
  }
  devise_for :users, controllers: {
    sessions: 'public/sessions',
    passwords: 'public/passwords',
    registrations: 'public/registrations',
  }

  # 管理者ゲストログイン
  devise_scope :admin do
    post '/admin/guest_session' => 'admin/sessions#guest_session'
  end
  # 会員ゲストログイン
  devise_scope :user do
    post '/users/guest_session' => 'public/sessions#guest_session'
  end

  scope module: :public do
    root 'homes#top'
    get '/about' => 'homes#about'
    resources :users,     only: [:show, :edit, :update, :destroy]
    resources :articles,  only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resource  :likes,     only: [:create, :destroy]
      resources :comments,  only: [:create, :destroy]
    end
    get '/user/unsubscribe' => 'users#unsubscribe'
    get '/search' => 'searches#search'
  end

  namespace :admin do
    resources :users,     only: [:index, :show, :edit, :update, :destroy]
    resources :articles,  only: [:index, :show, :edit, :update, :destroy]
    get '/search' => 'searches#search'
  end
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :article_images, dependent: :destroy
  accepts_attachments_for :article_images, attachment: :image, append: true

  validates :user_id, presence: true
  validates :title  , presence: true
  validates :content, presence: true

  def liked_by(user, article)
    Like.where(user_id: user.id, article_id: article.id).exists?
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  before_action :authenticate_admin!

  def index
    @last_article = Article.last
    @articles = Article
      .all
      .eager_load(:user, :likes, :comments, :article_images)
      .page(params[:page])
      .per(10)
      .reverse_order
  end

  def show
    set_article(params[:id])
  end

  def edit
    set_article(params[:id])
  end

  def update
    set_article(params{:id})
    if @article.update(article_params)
      redirect_to admin_article_path(@article.id), notice: "編集を適用しました"
    else
      render "edit"
    end
  end

  def destroy
    if @article = Article.find(params[:id]).destroy
      redirect_to admin_articles_path, notice: "記事を削除しました"
    else
      redirect_to "/", notice: "エラーが発生しました"
    end
  end

  private
  def article_params
    params.require(:article).permit(:title, :content, :user_id, article_images_images: [])
  end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/views/admin/articles/_list.html.erb
<% articles.each do |article| %>
  <div class="row mb-3 d-flex align-items-center">
    <div class="col-md-2 offset-md-1">
      <%= link_to admin_article_path(article.id) do %>
        <% if article.article_images.first %>
          <%= attachment_image_tag article.article_images.first, :image, class:"img-thumbnail", width:"200" %>
        <% else %>
          <%= image_tag "smart-home_640.jpg", width:"200" %>
        <% end %>
      <% end %>
    </div>
    <div class="col">
      <div class="row">
        <div class="col offset-md-1">
          <%= link_to article.title, admin_article_path(article.id), class:"h4" %>
        </div>
      </div>
      <div class="row">
        <div class="col offset-md-1">
          <%= article.user.name %>
          | <%= article.updated_at.strftime('%Y/%m/%d') %>
          | いいね: <%= article.likes_count %>件
          | コメント: <%= article.comments.size %>件
        </div>
      </div>
    </div>
    <div clas="col">
      <%= link_to "編集する", edit_admin_article_path(article.id), class:"btn btn-primary" %>
      <%= link_to "削除する", admin_article_path(article.id), method: :delete, class:"btn btn-danger", data: { confirm: '本当に削除しますか？' } %>
    </div>
  </div>
<% end %>

<div class="row mb-3">
  <div class="col-3 mx-auto">
    <%= paginate articles %>
  </div>
</div>

app/views/admin/articles/edit.html.erb
<div class="container">
  <div class="row mb-3">
    <div class="col p-0 alert alert-warning p-0 border-0">
      <% if @article.errors.any? %>
        <%= @article.errors.size %>件のエラーが発生しました
        <ul>
          <% @article.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>
  
  <div class="row mb-3">
    <div class="col">
      <h4>記事編集</h4>
    </div>
  </div>
  
  <%= form_with(model: @article, url: admin_article_path(params[:id])) do |f|  %>
    <div class="row mb-3">
      <div class="col-md-2">
        <h5>記事のタイトル</h5>
      </div>
      <div class="col">
        <%= f.text_field :title, autofocus: true, placeholder: "記事のタイトル", class:"col-md-5 form-control" %>
      </div>
    </div>
    <div class="row mb-3">
      <div class="col-md-2">
        <h5>本文</h5>
      </div>
      <div class="col">
        <%= f.text_area :content, rows: 15, placeholder: "記事の本文。改行できます。", class:"col-md-8 form-control" %>
      </div>
    </div>
    <div class="row mb-3">
      <div class="col-md-2">
        <h5>画像アップロード（複数選択可）</h5>
      </div>
      <div class="col">
        <%= f.attachment_field :article_images_images, multiple: true %>
      </div>
    </div>
    <div class="row mb-3">
      <div class="col-md-8 mx-auto">
        <%= f.submit "編集を確定する", class:"col-md-3 btn btn-success" %>
        <%= link_to "記事を削除する", admin_article_path(params[:id]), class:"col-md-3 btn btn-danger", method: :delete, data: { confirm: '本当に削除しますか？' } %>
      </div>
    </div>
  <% end %>

</div>

app/views/admin/articles/index.html.erb
<div class="container">
  <div class="row mb-3">
    <div class="col">
      <h4>記事リスト（全<%= @articles.total_count %>件）</h4>
    </div>
  </div>

  <%= render partial:"list", locals: {articles: @articles} %>
  
  <div class="row mb-3">
    <div class="col-2 mx-auto">
      <%= paginate @articles %>
    </div>
  </div>
</div>

app/views/admin/articles/show.html.erb
<div class="container">
  <div class="row mb-3">
    <div class="col">
      <h4><%= @article.title %></h4>
    </div>
      <div class="col-2 ml-auto">
        <%= link_to "編集する", edit_admin_article_path(@article.id), class:"btn btn-primary py-0" %>
      </div>
  </div>
  <!--slideshow skippr-->
  <div class="row mb-3">
    <div class="col-md-8 p-0 mx-auto text-center d-flex align-items-end">
      <div class="slideshow">
        <% if @article.article_images.present? %>
          <% @article.article_images.each do |img| %>
            <%= attachment_image_tag img, :image %>
          <% end %>
        <% else %>
          <%= image_tag "smart-home_640.jpg", width:"200" %>
        <% end %>
      </div>
    </div>
  </div>
  <!--article text content-->
  <div class="row mb-3">
    <div class="col-md-9 p-0 mx-auto">
      <%= simple_format(h(@article.content)) %>
    </div>
  </div>
  <!--Likes-->
  <div class="row mb-3 ">
    <div class="col-md-9 px-0 mx-auto">
      <span class="btn btn-primary">いいね♥<%= @article.likes.count %></span>
    </div>
  </div>
  <!--Comment list-->
  <% @article.comments.each do |comment| %>
    <div class="row mb-3">
      <div class="col-md-9 px-0 mx-auto">
        <%= comment.user.name %>
        <%= comment.body %>
      </div>
    </div>
  <% end %>
</div>