config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations',
  }
  devise_for :users, controllers: {
    sessions: 'public/sessions',
    passwords: 'public/passwords',
    registrations: 'public/registrations',
  }

  # 管理者ゲストログイン
  devise_scope :admin do
    post '/admin/guest_session' => 'admin/sessions#guest_session'
  end
  # 会員ゲストログイン
  devise_scope :user do
    post '/users/guest_session' => 'public/sessions#guest_session'
  end

  scope module: :public do
    root 'homes#top'
    get '/about' => 'homes#about'
    resources :users,     only: [:show, :edit, :update, :destroy]
    resources :articles,  only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      resource  :likes,     only: [:create, :destroy]
      resources :comments,  only: [:create, :destroy]
    end
    get '/user/unsubscribe' => 'users#unsubscribe'
    get '/search' => 'searches#search'
  end

  namespace :admin do
    resources :users,     only: [:index, :show, :edit, :update, :destroy]
    resources :articles,  only: [:index, :show, :edit, :update, :destroy]
    get '/search' => 'searches#search'
  end
end

app/views/layouts/_header.html.erb
      <div class="container">
        <div class="row">
          <div class="col">
            <nav class="navbar navbar-expand-md navbar-light px-0 bg-light">
              <%= link_to  root_path, class:"my-0" do %>
                <%= image_tag "logo.png", class:"logo" %>
              <% end %>
              <h6 class="my-auto offset-md-1">
                <% if current_user %>
                  <i class="h4 fas fa-user-check"></i>ようこそ、<%= current_user.name %>様！
                <% elsif current_admin %>
                  <i class="h4 fas fa-key"></i>管理者としてログインしています！
                <% else %>
                  <!--no text for non-member-->
                <% end %>
              </h6>
              
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarcontent" aria-controls="navbarcontent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              
              <div class="collapse navbar-collapse" id="navbarcontent">
                <ul class="navbar-nav ml-auto">
                  <!--member-->
                  <% if current_user %>
                    <li class="nav-item">
                      <%= link_to "マイページ", user_path(current_user.id), class:"nav-link" %>
                    </li>
                    <li class="nav-item">
                      <%= link_to "記事リスト", articles_path, class:"nav-link" %>
                    </li>
                    <li class="nav-item" type="button" data-toggle="collapse" data-target="#navbarsearch" aria-controls="navbarsearch" aria-expanded="false" aria-label="Toggle search">
                      <p class="nav-link mb-0">検索</p>
                    </li>
                    <li class="nav-item">
                      <%= link_to "投稿する", new_article_path, class:"nav-link" %>
                    </li>
                    <li class="nav-item">
                      <%= link_to "ログアウト", destroy_user_session_path, class:"nav-link", method: :delete %>
                    </li>
                    
                  <!--admin-->
                  <% elsif current_admin %>
                    <li class="nav-item">
                      <%= link_to "会員リスト", admin_users_path, class:"nav-link" %>
                    </li>
                    <li class="nav-item">
                      <%= link_to "記事リスト", admin_articles_path, class:"nav-link" %>
                    </li>
                    <li class="nav-item" type="button" data-toggle="collapse" data-target="#navbarsearch" aria-controls="navbarsearch" aria-expanded="false" aria-label="Toggle search">
                      <p class="nav-link mb-0">検索</p>
                    </li>
                    <li class="nav-item">
                      <%= link_to "ログアウト", destroy_admin_session_path, class:"nav-link", method: :delete %>
                    </li>
                    
                  <!--non-member-->
                  <% else %>
                    <li class="nav-item">
                      <%= link_to "About", about_path, class:"nav-link" %>
                    </li>
                    <li class="nav-item">
                      <%= link_to "記事リスト", articles_path, class:"nav-link" %>
                    </li>
                    <li class="nav-item" type="button" data-toggle="collapse" data-target="#navbarsearch" aria-controls="navbarsearch" aria-expanded="false" aria-label="Toggle search">
                      <p class="nav-link mb-0">検索</p>
                    </li>
                    <li class="nav-item">
                      <%= link_to "ログイン", new_user_session_path, class:"nav-link" %>
                    </li>
                    <li class="nav-item">
                      <%= link_to "管理者ログイン", new_admin_session_path, class:"nav-link" %>
                    </li>
                  <% end %>
                </ul>
              </div>
            </nav>
          </div>
          
          <%= render partial: 'layouts/searchform' %>
          <!-- has #navbarsearch in it -->
        </div>
      </div>

app/views/layouts/_searchform.html.erb
<!--admin：search（users, articles）-->
<% if current_admin %>
  <div class="col collapse navbar-collapse" id="navbarsearch">
    <%= form_with url: admin_search_path, method: :get, local: true, class:"form-inline" do |f| %>
      <%= f.text_field :word_for_search, class:"form-control", size:'40',placeholder: "キーワードを入力" %>
      <%= f.select :range_option, options_for_select([["記事検索"], ["会員検索"]]), {}, {class:"btn btn-outline-secondary"} %>
      <%= f.submit "Search", class:"btn btn-outline-success" %>
    <% end %>
  </div>
<!--member/non-member：search (articles) -->
<% else %>
  <div class="col collapse navbar-collapse" id="navbarsearch">
    <%= form_with url: search_path, method: :get, local: true, class:"form-inline" do |f| %>
      <%= f.text_field :word_for_search, class:"form-control", size:'40',placeholder: "キーワードを入力" %>
      <%= f.submit "Search", class:"btn btn-outline-success" %>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tectile｜趣味のIoTを楽しむための情報投稿サイト</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header class="shadow-sm mb-5 bg-light">
      <%= render partial: 'layouts/header' %>
      <!-- partial _searchbar in it -->
    </header>
    
    <div class="container">
      <div class="row">
        <h4 class="col p-0 alert alert-warning p-0 border-0" role="alert"><%= flash[:notice] %></h4>
      </div>
    </div>
    <%= yield %>
    
    <footer class="mt-5 bg-dark">
      <div class="container">
        <h6 class="text-light text-right py-5 mb-0">Copyright © TecTile All Rights Reserved.</h6>
      </div>
    </footer>
  </body>
</html>